#include "spi.h"


void SPI1_init(void){
	
	// PA5 SCK
	// PA7 MOSI

	RCC->AHB1ENR  |= RCC_AHB1ENR_GPIOAEN|RCC_AHB1ENR_GPIOBEN;  // Enable clock for GPIOA and GPIOE
	

	GPIOA->MODER  |= GPIO_MODER_MODER5_1|GPIO_MODER_MODER7_1;
  GPIOB->MODER  |= GPIO_MODER_MODER0_0|GPIO_MODER_MODER1_0;

	GPIOA->AFR[0] |= (5<<20)|(5<<28)|(5<<24);  // select AF5 (SPI1) for PA5,PA6, PA7 
	RCC->APB2ENR  |= RCC_APB2ENR_SPI1EN;  // Enable clock for SPI1
  SPI1->CR1    |= SPI_CR1_BR_0|SPI_CR1_BR_1|SPI_CR1_BR_2|SPI_CR1_MSTR|SPI_CR1_SSM|SPI_CR1_SSI;
  SPI1->CR1 |= SPI_CR1_SPE;


}


